[package]
name = "fuzzdelsol"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.17"
solana_rbpf = "0.8.5"
rand = "0.8"

libafl = "0.13.2"
libafl_bolts = "0.13.2"
hex = "0.4"

once_cell = "1.19.0"
